### ISSUE TITLE
Additional Questions to Consider

### ISSUE THREAD

**Issue by henry131** [henry131/weather-api-with-owm#3]
## TODO

*Additional questions to Developer Task*

* [ ]  If I wanted the temperature in Kelvin rather than celcius, how could I specify this in API calls?
  - .../temperature/kelvin
* [ ] How would you test this REST service? 
  - Postman?
* [ ] How would you check the code coverage of your tests? 
  - coverage.py?
* [ ] How could the API be documented for third-parties to use?
  - TokenAuth? - a database of users?
 * [ ] What would you suggest is needed to do daily forecast recoveries from openweather.org, keeping the web service up to date?
   - Regular checks of owm returned json structure - email alert if any changes(?)
   - Use cache / database to reduce api calls made to OWM where same data requested (implement here?)
